# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: German Indicators For The Sustainable Development Goals
description: Data Platform Prototype
baseurl: "/sdg-indicators" # the subpath of your site, e.g. /blog
url: ""
data_dir: data
environment: staging
remote_data_prefix: "https://G205SDGs.github.io/sdg-data"
# URL for the "Edit Data" button on indicators.
data_edit_url: http://prose.io/#open-sdg/open-sdg-data-starter/edit/develop/data/indicator_[id].csv
# URL for the "Edit Metadata" button on indicators.
metadata_edit_url: http://prose.io/#open-sdg/open-sdg-data-starter/edit/develop/meta/[id].md
# permalink: /news/:year/:month/:day/:title.html


# Automatically create indicator pages, goal pages,
# and some other required pages.
create_indicators:
  layout: indicator
create_goals:
  layout: goal
create_pages: true


analytics:
  ga_prod: ''

###################################################################################################
email_contacts:
  questions: sdg-indicators@destatis.de
  suggestions: sdg-indicators@destatis.de
  functional: sdg-indicators@destatis.de
###################################################################################################


# Build settings
markdown: kramdown

exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE

# International Support
# Eg name: Australia and adjective: Australian.
country:
  name: Germany
  adjective: German

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# The list of languages that are translated. The first one is the default.
languages:
    - de
    - en

# Menu
menu:
  # Use these to customise the main navigation.
  - path: /
    translation_key: general.goals
  - path: /reporting-status/
    translation_key: menu.reporting_status
  - path: /about/
    translation_key: menu.about
  - path: /guidance/
    translation_key: menu.guidance


footer_menu:
  - path: mailto:my-email-address@example.com
    translation_key: menu.contact_us
  - path: https://twitter.com/MyTwitterAccount
    translation_key: general.twitter

# Configure the text (or "translation key") to be used on the
# non-global metadata tab.
non_global_metadata: indicator.national_metadata

plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

# Use a remote Jekyll theme.
remote_theme: open-sdg/open-sdg@1.0.0-beta4
goal_image_base: https://g205sdgs.github.io/sdg-indicators/assets/img/goals


custom_js:
  - /assets/js/custom.js
